Blog/urls.py
from django.urls import path
from . import views
app_name = 'Blog'
urlpatterns= [
   path('', views.index.as_view(template_name="Blog/blogpost_list.html"), name='blogpost'),
    path('<slug:pk>/authors/', views.authors.as_view(), name='authors'),
 ]

Blog/models.py
from django.db import models
from django.utils import dates, timezone


# Create your models here.
class Authors(models.Model):
    Name = models.CharField(max_length=100)
    Genre= models.CharField(max_length=100)
    Bio = models.TextField()
    def __str__(self):
        return self.Name

class blogPost(models.Model):
    Title= models.CharField(max_length=100)
    Text = models. TextField()
    Created_date = models.DateTimeField(default=timezone.now)
    Updated_date = models.DateTimeField(blank=True, null=True)
    Author = models.ForeignKey(Authors, related_name='blogPost', on_delete=models.CASCADE)
    def __str__(self):
        return self.Title

Blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from .models import Authors,blogPost


# Create your views here.
class index(ListView):
    context_object_name = 'blogpost'
    model = blogPost
    template_name = 'Blog/blogpost_list.html/'

class authors(DetailView):
    context_object_name = 'authors'
    model = Authors
    template_name = 'Blog/author_detail.html/'

Blog/templates/Blog/author_detail.html
{% extends 'Blog/index.html'%}
{% block body_block%}
<div class="jumbotron">

    <h1> Hi! I am{{authors.Name}}</h1>
  <p> {{authors.Bio}}</p>

</div>
{%endblock%}

Blog/templates/Blog/authors_list.html
{% extends 'Blog/index.html'%}
{% block body_block%}
<div class="jumbotron">
<h1>  </h1>

    <h1>{{authors.Name}}</h1>
  <p> {{authors.Bio}}</p>

</div>
{%endblock%}

Blog/templates/Blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title> Base</title>
    <style>

  footer{
  background-color: #f1c11a;

  clip-path: polygon(0 0, 15% 0, 50% 20%, 85% 0, 100% 0, 100% 100%, 0 100%, 0 0);
  margin-top: -8vh;
  text-align: center;
  padding-top: 15vh;
  padding-bottom: 50px;
}
</style>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">My Blogs </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'admin:index'%}">admin</a></li>
      <li><a href="{% url 'Blog:blogpost'%}"> Blogs </a></li>

    </ul>
  </div>
</nav>



 {% block body_block%}
{% endblock %}
<footer>
    @ 2020
    <p class="fo-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>

    <div class=" address">
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-home" aria-hidden="true"></i>Far Western University</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-phone" aria-hidden="true"></i>+34253245324</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><a href="mailto:info@example.com"><i class="fa fa-envelope-o" aria-hidden="true"></i>info@example1.com</a></p>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
    </footer>

 </div>
</body>
</html>

Blog/templates/Blog/blogpost_list.html
{% extends 'Blog/index.html'%}
{% load static %}
{% block body_block%}
<style>
.btn{
  background-color: transparent;
  border: 3px solid black;
  padding: 15px 35px;
  font-weight: bolder;
  text-decoration: none;
  color: black;
  margin-right: 15px;
  transition: all 400ms ease-in-out;
  text-decoration: none;
}

}
</style>
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'Writing-Blogs.jpg' %}" class="d-block w-100 h-5vh " alt="..."  height = 480vh>
    </div>
    <div class="carousel-item">
      <img src="{% static 'image.PNG' %}" class="d-block w-100 h-5 " alt="..." height = 480vh>
    </div>
    <div class="carousel-item">
      <img src="{% static 'coffee.jpg' %}" class="d-block w-100 h-5 " alt="..." height = 480vh>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron">
<h1> Our Blogs </h1>

 {% for blogs in blogpost%}
    <h1> {{blogs.Title}}</h1>
  <p> {{blogs.Text}}</p>

  <li><a class="btn" href="{% url 'Blog:authors' blogs.pk %}">Click to know about Author </a></li>
  {% endfor %}
</div>


</div>



{% endblock%}

Blog/templates/Blog/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <title> Base</title>
    <style>

  footer{
  background-color: #f1c11a;

  clip-path: polygon(0 0, 15% 0, 50% 20%, 85% 0, 100% 0, 100% 100%, 0 100%, 0 0);
  margin-top: -8vh;
  text-align: center;
  padding-top: 15vh;
  padding-bottom: 50px;
}
</style>
</head>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">My Blogs </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li><a href="{% url 'admin:index'%}">admin</a></li>
      <li><a href="{% url 'Blog:blogpost'%}"> Blogs </a></li>

    </ul>
  </div>
</nav>



 {% block body_block%}
{% endblock %}
<footer>
    @ 2020
    <p class="fo-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>

    <div class=" address">
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-home" aria-hidden="true"></i>Far Western University</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><i class="fa fa-phone" aria-hidden="true"></i>+34253245324</p>
                    </div>
                    <div class="col-md-4 fo-grid1">
                        <p><a href="mailto:info@example.com"><i class="fa fa-envelope-o" aria-hidden="true"></i>info@example1.com</a></p>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
    </footer>

 </div>
</body>
</html>